export const dataList =[
  {
    id: 'email_1',
    icon: '1',
    relevancy: '1',
    attachment: '1',
    comments: 'here',
    author: 'ccc',
    subject: 'xxx',
    date: '02/28/2019',
    hotwords_hits: 'xxx',
    status: 'xxx',
    capture_method: 'xx',
    type: 'xx',
    escalation_status: 'xx',
    escalation_owner: 'xx',
    escalated_by: 'xx',
    children: [
      {
        id: 'email_1',
        icon: '10',
        relevancy: '1',
        attachment: '1',
        comments: 'here',
        author: 'ccc',
        subject: 'xxx',
        date: '02/28/2019',
        hotwords_hits: 'xxx',
        status: 'xxx',
        capture_method: 'xx',
        type: 'xx',
        escalation_status: 'xx',
        escalation_owner: 'xx',
        escalated_by: 'xx'
      },
      {
        id: 'email_1',
        icon: '11',
        relevancy: '1',
        attachment: '1',
        comments: 'here',
        author: 'ccc',
        subject: 'xxx',
        date: '02/28/2019',
        hotwords_hits: 'xxx',
        status: 'xxx',
        capture_method: 'xx',
        type: 'xx',
        escalation_status: 'xx',
        escalation_owner: 'xx',
        escalated_by: 'xx'
      }
    ]
  },
  {
    id: 'email_1',
    icon: '2',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '02/29/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  },
  {
    id: 'email_1',
    icon: '3',
    relevancy: '1',
    attachment: '1',
    comments: 'here',
    author: 'ccc',
    subject: 'xxx',
    date: '02/28/2019',
    hotwords_hits: 'xxx',
    status: 'xxx',
    capture_method: 'xx',
    type: 'xx',
    escalation_status: 'xx',
    escalation_owner: 'xx',
    escalated_by: 'xx'
  },
  {
    id: 'email_1',
    icon: '4',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '02/29/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  },
  {
    id: 'email_1',
    icon: '5',
    relevancy: '1',
    attachment: '1',
    comments: 'here',
    author: 'ccc',
    subject: 'xxx',
    date: '02/29/2019',
    hotwords_hits: 'xxx',
    status: 'xxx',
    capture_method: 'xx',
    type: 'xx',
    escalation_status: 'xx',
    escalation_owner: 'xx',
    escalated_by: 'xx'
  },
  {
    id: 'email_1',
    icon: '6',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '02/29/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  },
  {
    id: 'email_1',
    icon: '7',
    relevancy: '1',
    attachment: '1',
    comments: 'here',
    author: 'ccc',
    subject: 'xxx',
    date: '02/29/2019',
    hotwords_hits: 'xxx',
    status: 'xxx',
    capture_method: 'xx',
    type: 'xx',
    escalation_status: 'xx',
    escalation_owner: 'xx',
    escalated_by: 'xx'
  },
  {
    id: 'email_1',
    icon: '8',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '02/28/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  },
  {
    id: 'email_1',
    icon: '9',
    relevancy: '1',
    attachment: '1',
    comments: 'here',
    author: 'ccc',
    subject: 'xxx',
    date: '02/29/2019',
    hotwords_hits: 'xxx',
    status: 'xxx',
    capture_method: 'xx',
    type: 'xx',
    escalation_status: 'xx',
    escalation_owner: 'xx',
    escalated_by: 'xx'
  },
  {
    id: 'email_1',
    icon: '10',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '02/28/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  },
  {
    id: 'email_1',
    icon: '11',
    relevancy: 'x',
    attachment: 'zz',
    comments: 'here2',
    author: 'gg',
    subject: 'gg',
    date: '03/28/2019',
    hotwords_hits: 'gg',
    status: 'gg',
    capture_method: 'gg',
    type: 'gg',
    escalation_status: 'ff',
    escalation_owner: 'ss',
    escalated_by: 'g'
  }
]